### PR TITLE
feat: Port extension to Gnome 45

### LINKED ISSUE #9: Support Gnome 45
Could be more effort than other GNOME releases, see https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45

### PR DESCRIPTION
**Pull request by DrOptix**
Guides followed:
- https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/
- https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

Closes #9

### CODE REVIEW

**Comment by ujwalnk** [comment]
The port seems to be working fine on Fedora 39, runnning gnome 45

**Comment by MostFrabjous** [comment]
Also fine on Arch with Gnome-Shell 45.1

**Review by ujwalnk — APPROVED** [review]
Works fine on Fedora 39, Arch & Ubuntu, running Gnome 45.1

**Comment by DrOptix** [comment]
@LeonMatthes can you give your final opinion on this one?
Thank you!

**Review by LeonMatthes — APPROVED** [review]
Hi, thank you for the port :1st_place_medal: 

I won't be able to test this myself as I'm not yet on fedora 39/GNOME 45.
However, I take it from the porting guide and all the positive feedback that this does indeed work.

The code is also cleaner than you found it, so that's a +1 from me :+1: 

I have noticed that you used prettier to format the code (which isn't a bad idea), however in future please split changes like this up. Either into separate commits in the same PR, or into two separate PRs.

Reviewing code that has changed both formatting and function is much harder than code that has not been reformatted. Subtle bugs can sneak in easily that way.
I'll still merge this, as the porting itself is relatively straightforward.
But please keep this in mind for future PRs. Thank you :blush:

**Comment by DrOptix** [comment]
First thank you for approving this PR. I understand. About formatting, I'm used to review PRs most of the time as their final digested diff. Very rarely I review particular commits, but I understand your point and I'll try to work on it becoming my new habit, splitting style and function commits.

**Pull request merged**
